latest_day := "2"

[no-exit-message]
test DAY:
    pytest --capture=no tests/test_day{{DAY}}.py

test-all:
    pytest tests

[no-exit-message]
run DAY:
    python3 src/main.py {{DAY}}

run-all:
    for i in $(seq 1 {{latest_day}}); do \
    echo ""; \
    just run $i; \
    done
