[no-exit-message]
test DAY:
    pytest --capture=no tests/test_day{{DAY}}.py

test-all:
    pytest tests

[no-exit-message]
run DAY:
    PYTHONPATH=src python3 -m src.main {{DAY}}

run-all:
    for file in `ls src | grep day`; do \
        echo ""; \
        just run "${file:3}"; \
    done
