[tool.pyright]
include = ["src", "tests"]
extraPaths = ["src"]
typeCheckingMode = "strict"

[tool.pylint.MAIN]
init-hook = "import sys; sys.path.append('src')"
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
